# Generated by Django 3.0.4 on 2020-03-12 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc_bball.Color')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc_bball.State')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mpg', models.IntegerField()),
                ('ppg', models.IntegerField()),
                ('rpg', models.IntegerField()),
                ('apg', models.IntegerField()),
                ('spg', models.DecimalField(decimal_places=1, max_digits=4)),
                ('bpg', models.DecimalField(decimal_places=1, max_digits=4)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc_bball.Team')),
            ],
        ),
    ]
