# Generated by Django 3.0.4 on 2020-03-13 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_bball', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='color',
            table='Color',
        ),
        migrations.AlterModelTable(
            name='player',
            table='Player',
        ),
        migrations.AlterModelTable(
            name='state',
            table='State',
        ),
        migrations.AlterModelTable(
            name='team',
            table='Team',
        ),
    ]
