# Generated by Django 3.0.4 on 2020-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_bball', '0002_auto_20200313_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='uniform_num',
            field=models.IntegerField(null=True),
        ),
    ]
